# Generated by Django 2.2 on 2019-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtest',
            name='incorret_questions',
            field=models.ManyToManyField(blank=True, related_name='passed_test_incorrect_questions', to='competence_center.Question'),
        ),
    ]
