# Generated by Django 2.2 on 2019-11-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0002_passedtest_incorret_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passedtest',
            old_name='incorret_questions',
            new_name='incorrect_questions',
        ),
    ]
