# Generated by Django 2.2 on 2019-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0004_auto_20191109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedtest',
            name='incorrect_questions',
            field=models.ManyToManyField(blank=True, default=[], to='competence_center.Question'),
        ),
    ]
