# Generated by Django 2.2 on 2019-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0005_auto_20191109_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtest',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
