# Generated by Django 2.2 on 2019-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0006_passedtest_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtest',
            name='min_score_percent_for_success',
            field=models.IntegerField(default=50),
        ),
    ]
