# Generated by Django 2.2 on 2019-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0007_passedtest_min_score_percent_for_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_literature',
            field=models.URLField(blank=True),
        ),
    ]
