# Generated by Django 2.2 on 2019-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_center', '0008_question_additional_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtest',
            name='recommendations',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
